"""add pharmacy module

Revision ID: 060b7413b740
Revises: 22aeec81a68b
Create Date: 2026-06-24 20:40:32.576839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060b7413b740'
down_revision = '22aeec81a68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_code', sa.String(length=50), nullable=False),
    sa.Column('medication_name', sa.String(length=150), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_code')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispensings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('dispensed_by', sa.String(length=150), nullable=True),
    sa.Column('dispensing_notes', sa.Text(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispensings')
    op.drop_table('prescriptions')
    op.drop_table('medications')
    # ### end Alembic commands ###
