"""add radiology module

Revision ID: 22aeec81a68b
Revises: 826a6742d603
Create Date: 2026-06-24 17:31:30.763279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aeec81a68b'
down_revision = '826a6742d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radiology_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('modality', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_code')
    )
    op.create_table('radiology_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('radiology_test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['radiology_test_id'], ['radiology_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radiology_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiology_order_id', sa.Integer(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('impression', sa.Text(), nullable=False),
    sa.Column('report_status', sa.String(length=50), nullable=True),
    sa.Column('reported_by', sa.String(length=150), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['radiology_order_id'], ['radiology_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radiology_reports')
    op.drop_table('radiology_orders')
    op.drop_table('radiology_tests')
    # ### end Alembic commands ###
