"""add laboratory module

Revision ID: 826a6742d603
Revises: d2bcc68534b3
Create Date: 2026-06-24 01:00:41.125781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826a6742d603'
down_revision = 'd2bcc68534b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_code')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('lab_test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_order_id', sa.Integer(), nullable=False),
    sa.Column('result_value', sa.String(length=100), nullable=False),
    sa.Column('result_unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=150), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_results')
    op.drop_table('lab_orders')
    op.drop_table('lab_tests')
    # ### end Alembic commands ###
