"""add problem list module

Revision ID: 9525aa03f3f9
Revises: b28b2fc71aef
Create Date: 2026-07-02 02:42:14.860783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9525aa03f3f9'
down_revision = 'b28b2fc71aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_name', sa.String(length=200), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('problem_type', sa.String(length=50), nullable=True),
    sa.Column('clinical_status', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
